version: "3.10.9"

services:
  hw_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "hwdb"
      POSTGRES_USER: "hwdb_user"
      POSTGRES_PASSWORD: "hwdb_passwd"
      PGDATA: "/data/pgdata"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
    ports:
      - "5432:5432"